FROM continuumio/miniconda3

# 设置环境变量
ENV PATH=/opt/conda/bin:$PATH

# 内部挂载点
VOLUME /huixiangdou
WORKDIR /huixiangdou

# 创建并激活 py38 环境，并安装依赖包
RUN conda create --name py38 python=3.8 -y && \
    conda run -n py38 pip install -r requirements-cpu.txt && \
    conda clean --all -f -y

# 暴露 gradio 和 http 服务端口
EXPOSE 7860
EXPOSE 23333

# 选择启动提特征还是运行服务
ENTRYPOINT ["./entrypoint.sh"]
CMD ["setup_feature", "start_service"]
