version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

formats:
    - epub

sphinx:
  configuration: docs/en/conf.py

python:
  install:
    - requirements: requirements/docs.txt
